name: Fuzz parser

on:
  pull_request:
    branches:
      - "**"
    paths:
      - src/parser.c
      - src/scanner.c
      - src/tag.h
  push:
    branches:
      - "master"
    paths:
      - src/parser.c
      - src/scanner.c
      - src/tag.h
  workflow_dispatch:

jobs:
  test:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/fuzz-action@v4
        with:
          directory: .
          corpus: test/corpus
